CREATE TABLE IF NOT EXISTS Users (
  user_id SERIAL PRIMARY KEY,
  username VARCHAR(255) UNIQUE NOT NULL,
  first_name VARCHAR(255) UNIQUE NOT NULL,
  last_name VARCHAR(255) UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Sessions (
  session_id UUID PRIMARY KEY DEFAULT UUIDv7(),
  user_id INTEGER NOT NULL REFERENCES Users(user_id),
  ip_address INET NOT NULL,
  start_timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  session_token CHAR(32) NOT NULL
);
